import { createServerClient, type CookieOptions } from '@supabase/ssr';
import { cookies } from 'next/headers';
import { NextResponse } from 'next/server';

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);
  const code = searchParams.get('code');
  const next = searchParams.get('next') ?? '/onboarding';

  if (code) {
    const cookieStore = await cookies();

    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() {
            return cookieStore.getAll();
          },
          setAll(cookiesToSet: { name: string; value: string; options: CookieOptions }[]) {
            cookiesToSet.forEach(({ name, value, options }) =>
              cookieStore.set(name, value, options)
            );
          },
        },
      }
    );

    const { error } = await supabase.auth.exchangeCodeForSession(code);

    if (!error) {
      // Kullanicinin onboarding'i tamamlayip tamamlamadigini kontrol et
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        const { data: profile } = await supabase
          .from('users')
          .select('name, avatar_id')
          .eq('id', user.id)
          .single();

        // Profil varsa kontrol et: onboarding tamamlanmis mi?
        if (profile && profile.name && profile.name !== '') {
          const emailPrefix = user.email?.split('@')[0] || '';
          const googleName = user.user_metadata?.full_name || user.user_metadata?.name || '';

          // Isim hÃ¢lÃ¢ auto-generated (email prefix veya Google display name) VE
          // avatar hÃ¢lÃ¢ default â†’ onboarding tamamlanmamis
          const isAutoGenerated =
            profile.avatar_id === 1 &&
            (profile.name === emailPrefix || profile.name === googleName);

          if (isAutoGenerated) {
            return NextResponse.redirect(`${origin}/onboarding`);
          }
          return NextResponse.redirect(`${origin}/dashboard`);
        }
      }
      return NextResponse.redirect(`${origin}${next}`);
    }
  }

  // Auth hatasi â†’ auth sayfasina geri dön
  return NextResponse.redirect(`${origin}/auth?error=callback_failed`);
}

