'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase-client';
import { useAuthStore } from '@/stores/auth-store';
import { COPY, AVATARS, FREE_DAILY_LIMIT, getTrustLevel } from '@/lib/constants';
import { motion } from 'framer-motion';
import { RehabBanner } from '@/components/trust/TrustComponents';
import { DailyQuestCard, WeeklyQuestPanel, HIDDEN_QUEST_INFO } from '@/components/quests/QuestComponents';
import type { DailyQuest, WeeklyQuest } from '@/components/quests/QuestComponents';
import { BottomNav } from '@/components/layout/BottomNav';
import type { User, UserLimit } from '@/types/database';

interface ActiveMatchInfo {
  matchId: string;
  sessionId: string;
  state: string;
}

export default function DashboardPage() {
  const router = useRouter();
  const { user, setUser } = useAuthStore();
  const [dailyUsed, setDailyUsed] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [activeMatch, setActiveMatch] = useState<ActiveMatchInfo | null>(null);
  const [dailyQuest, setDailyQuest] = useState<DailyQuest | null>(null);
  const [weeklyQuest, setWeeklyQuest] = useState<WeeklyQuest | null>(null);
  const [hiddenCount, setHiddenCount] = useState(0);

  useEffect(() => {
    const supabase = createClient();

    async function load() {
      const { data: { user: authUser } } = await supabase.auth.getUser();
      if (!authUser) {
        router.push('/auth');
        return;
      }

      // User profili
      const { data: profile, error: profileError } = await supabase
        .from('users')
        .select('*')
        .eq('id', authUser.id)
        .maybeSingle();

      if (profileError) {
        console.error('Profil yüklenemedi:', profileError.message);
        // Tablo yoksa veya trigger çalismadiysa â†’ kullaniciyi manuel olustur
        if (profileError.code === '42P01' || !profile) {
          const { data: newProfile } = await supabase
            .from('users')
            .upsert({
              id: authUser.id,
              email: authUser.email ?? '',
              name: authUser.email?.split('@')[0] ?? 'Kullanici',
              avatar_id: 1,
            })
            .select('*')
            .single();
          if (newProfile) {
            // Yeni profil olustu â†’ onboarding'e yönlendir
            router.push('/onboarding');
            return;
          }
        }
      } else if (profile) {
        // ONBOARDING GATE: Profil varsa onboarding tamamlanmis mi kontrol et
        // avatar_id === 1 (default) VE name auto-generated ise â†’ onboarding gerekli
        const emailPrefix = authUser.email?.split('@')[0] || '';
        const googleName = authUser.user_metadata?.full_name || authUser.user_metadata?.name || '';
        const isAutoGenerated =
          profile.avatar_id === 1 &&
          (profile.name === emailPrefix || profile.name === googleName || profile.name === '');

        if (isAutoGenerated) {
          router.push('/onboarding');
          return;
        }

        setUser(profile as User);
      } else {
        // Profil yok â€” trigger çalismamis, manuel olustur
        const { data: newProfile } = await supabase
          .from('users')
          .upsert({
            id: authUser.id,
            email: authUser.email ?? '',
            name: authUser.email?.split('@')[0] ?? 'Kullanici',
            avatar_id: 1,
          })
          .select('*')
          .single();
        if (newProfile) setUser(newProfile as User);
      }

      // Günlük limit (maybeSingle â€” satir yoksa null döner, 406 hata vermez)
      const today = new Date().toISOString().split('T')[0];
      const { data: limit } = await supabase
        .from('user_limits')
        .select('sessions_used')
        .eq('user_id', authUser.id)
        .eq('date', today)
        .maybeSingle();

      setDailyUsed((limit as UserLimit | null)?.sessions_used ?? 0);

      // Check for active or broken matches using RPC (validates heartbeat recency)
      const { data: activeMatchResult } = await supabase.rpc('get_active_match');

      if (activeMatchResult && activeMatchResult.has_active) {
        setActiveMatch({
          matchId: activeMatchResult.match_id,
          sessionId: activeMatchResult.session_id,
          state: activeMatchResult.can_rejoin ? 'broken' : 'active',
        });
      }

      // Load quest data from user metadata
      const userProfile = profile as User | null;
      if (userProfile?.metadata) {
        const meta = userProfile.metadata as { quests?: { daily?: DailyQuest; weekly?: WeeklyQuest; hidden_completed?: string[] } };
        if (!meta.quests) {
          // Initialize quests for first-time users
          await supabase.rpc('init_user_quests', { p_user_id: authUser.id });
          // Refetch metadata
          const { data: updated } = await supabase.from('users').select('metadata').eq('id', authUser.id).single();
          if (updated?.metadata) {
            const m = updated.metadata as { quests?: { daily?: DailyQuest; weekly?: WeeklyQuest; hidden_completed?: string[] } };
            if (m.quests?.daily) setDailyQuest(m.quests.daily);
            if (m.quests?.weekly) setWeeklyQuest(m.quests.weekly);
            setHiddenCount((m.quests?.hidden_completed ?? []).length);
          }
        } else {
          if (meta.quests.daily) setDailyQuest(meta.quests.daily);
          if (meta.quests.weekly) setWeeklyQuest(meta.quests.weekly);
          setHiddenCount((meta.quests.hidden_completed ?? []).length);
        }
      }

      setIsLoading(false);
    }

    load();
  }, [router, setUser]);

  const canStartSession = user?.is_premium || dailyUsed < FREE_DAILY_LIMIT;
  const avatar = AVATARS.find(a => a.id === user?.avatar_id) ?? AVATARS[0];

  const handleLogout = async () => {
    const supabase = createClient();
    await supabase.auth.signOut();
    setUser(null);
    router.push('/auth');
  };

  const handleRejoin = async () => {
    if (!activeMatch) return;

    if (activeMatch.state === 'active') {
      router.push(`/session/active?id=${activeMatch.sessionId}`);
    } else if (activeMatch.state === 'preparing') {
      router.push(`/session/prepare?id=${activeMatch.sessionId}`);
    } else if (activeMatch.state === 'broken') {
      const supabase = createClient();
      const { data, error } = await supabase.rpc('rejoin_match', {
        p_match_id: activeMatch.matchId,
      });

      if (error || !(data as { success: boolean })?.success) {
        setActiveMatch(null);
        return;
      }

      router.push(`/session/active?id=${activeMatch.sessionId}`);
    }
  };

  const handleDismissMatch = async () => {
    if (!activeMatch) return;
    const supabase = createClient();

    // Complete the match so it's no longer found
    await supabase.rpc('complete_match', { p_match_id: activeMatch.matchId });

    // Abandon the session
    await supabase
      .from('sessions')
      .update({ status: 'abandoned', ended_at: new Date().toISOString() })
      .eq('id', activeMatch.sessionId)
      .in('status', ['waiting', 'preparing', 'active']);

    setActiveMatch(null);
  };

  if (isLoading || !user) {
    return (
      <div className="min-h-screen bg-[#1a1a2e] flex items-center justify-center">
        <div className="text-white/50 text-lg">Yükleniyor...</div>
      </div>
    );
  }

  // Trust level info
  const trustLevel = user ? getTrustLevel(user.trust_score) : null;
  const isRestricted = user && user.trust_score < 50;

  return (
    <div className="min-h-screen bg-gradient-to-b from-[#1a1a2e] via-[#16213e] to-[#0f3460] px-4 py-8 pb-24">
      <div className="max-w-sm mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-3">
            <span className="text-3xl">{avatar.emoji}</span>
            <div>
              <h1 className="text-white font-semibold">{user.name}</h1>
              <p className="text-gray-500 text-sm">Lv.{user.level} · {user.xp} XP</p>`n              <p className="text-gray-400 text-xs mt-1">Hazirsan basliyoruz.</p>
            </div>
          </div>
          <button
            onClick={handleLogout}
            className="text-gray-500 hover:text-gray-300 text-sm transition-colors"
          >
            Çikis
          </button>
        </div>

        {/* Stat kartlari */}
        <div className="grid grid-cols-3 gap-3 mb-8">
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="bg-white/5 rounded-xl p-4 text-center"
          >
            <p className="text-2xl font-bold text-[#ffcb77]">
              {user.current_streak}
            </p>
            <p className="text-gray-500 text-xs mt-1">{COPY.DASHBOARD_STREAK}</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="bg-white/5 rounded-xl p-4 text-center"
          >
            <div className="flex items-center justify-center gap-1 mb-1">
              <span className="text-lg">{trustLevel?.emoji}</span>
              <span
                className="text-2xl font-bold"
                style={{ color: trustLevel?.color }}
              >
                {user.trust_score}
              </span>
            </div>
            <p className="text-gray-500 text-xs">{COPY.DASHBOARD_TRUST}</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="bg-white/5 rounded-xl p-4 text-center"
          >
            <p className="text-2xl font-bold text-white">
              {user.completed_sessions}
            </p>
            <p className="text-gray-500 text-xs mt-1">{COPY.DASHBOARD_SESSIONS}</p>
          </motion.div>
        </div>

        {/* Streak göstergesi */}
        {user.current_streak > 0 && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="bg-[#ffcb77]/10 border border-[#ffcb77]/20 rounded-xl p-4 mb-6 text-center"
          >
            <span className="text-2xl">ğŸ”¥</span>
            <p className="text-[#ffcb77] text-sm mt-1">
              {user.current_streak} günlük seri! Devam et.
            </p>
          </motion.div>
        )}

        {/* Quest section */}
        {(dailyQuest || weeklyQuest) && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.35 }}
            className="mb-6 space-y-3"
          >
            <div className="flex items-center justify-between">
              <p className="text-gray-500 text-xs uppercase tracking-wide">Görevler</p>
              <p className="text-gray-600 text-xs">
                {hiddenCount}/{Object.keys(HIDDEN_QUEST_INFO).length} gizli görev
              </p>
            </div>
            <DailyQuestCard quest={dailyQuest} />
            <WeeklyQuestPanel quest={weeklyQuest} />
          </motion.div>
        )}

        {/* Active match rejoin banner */}
        {activeMatch && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-orange-500/10 border border-orange-500/30 rounded-xl p-4 mb-6"
          >
            <div className="flex items-center gap-3">
              <span className="text-2xl">{activeMatch.state === 'active' ? 'â±ï¸' : 'ğŸ”„'}</span>
              <div className="flex-1">
                <p className="text-white text-sm font-medium">
                  {activeMatch.state === 'active'
                    ? 'Devam eden seansin var!'
                    : 'Eslesmeye geri dönebilirsin!'}
                </p>
                <p className="text-gray-400 text-xs">
                  {activeMatch.state === 'active'
                    ? 'Aktif bir seans devam ediyor.'
                    : 'Esin hala bekliyor olabilir.'}
                </p>
              </div>
              <div className="flex flex-col gap-1">
                <button
                  onClick={handleRejoin}
                  className="bg-[#ffcb77] text-[#1a1a2e] px-4 py-2 rounded-xl text-sm font-semibold whitespace-nowrap"
                >
                  Geri Dön
                </button>
                <button
                  onClick={handleDismissMatch}
                  className="text-gray-500 text-xs hover:text-gray-300 transition-colors"
                >
                  Kapat
                </button>
              </div>
            </div>
          </motion.div>
        )}

        {/* Günlük kullanim */}
        {!user.is_premium && (
          <div className="text-center text-gray-500 text-sm mb-4">
            Bugün: {dailyUsed}/{FREE_DAILY_LIMIT} seans
          </div>
        )}

        {/* Rehabilitation Banner (trust < 50) */}
        {isRestricted && (
          <RehabBanner userId={user.id} />
        )}

        {        {/* Ana CTA Grid */}
        <div className="mb-8 grid grid-cols-1 gap-3">
          <motion.button
            whileHover={{ scale: (canStartSession && !isRestricted) ? 1.02 : 1 }}
            whileTap={{ scale: (canStartSession && !isRestricted) ? 0.98 : 1 }}
            onClick={() => {
              if (!canStartSession || isRestricted) return;
              router.push('/session/quick-match');
            }}
            disabled={!canStartSession || isRestricted}
            className={`
              w-full py-4 rounded-2xl font-semibold text-lg transition-all text-left px-5
              ${(canStartSession && !isRestricted)
                ? 'bg-[#ffcb77] text-[#1a1a2e] shadow-lg shadow-[#ffcb77]/20'
                : 'bg-white/10 text-gray-500 cursor-not-allowed'
              }
            `}
          >
            <div className="text-lg">
              {isRestricted
                ? 'Solo Modda Devam Et'
                : (canStartSession ? '?? Hemen Basla' : 'Günlük limit doldu')}
            </div>
            <div className="text-xs mt-1">
              {isRestricted
                ? 'Topluluk güvenligi için kisa bir ara.'
                : 'Sessizce eslik edecegim.'}
            </div>
          </motion.button>

          <button
            onClick={() => router.push('/profile')}
            className="w-full py-4 rounded-2xl font-semibold text-lg transition-all text-left px-5 bg-white/5 text-white hover:bg-white/10"
          >
            <div className="text-lg">?? Profilim</div>
            <div className="text-xs mt-1 text-gray-400">Sana özel ayarlar</div>
          </button>

          <button
            onClick={() => router.push('/help')}
            className="w-full py-4 rounded-2xl font-semibold text-lg transition-all text-left px-5 bg-white/5 text-white hover:bg-white/10"
          >
            <div className="text-lg">? Yardim</div>
            <div className="text-xs mt-1 text-gray-400">Nasil çalistigini ögren</div>
          </button>
        </div>

        {!canStartSession && (
          <p className="text-gray-600 text-xs text-center mt-3">
            Yarin tekrar gel veya sinirsiz erisim için premium&apos;a geç.
          </p>
        )}

        {/* Toplam odak */}}
        <div className="mt-10 text-center">
          <p className="text-gray-600 text-sm">
            Toplam {Math.floor(user.total_minutes / 60)} saat {user.total_minutes % 60} dk odaklandin
          </p>
        </div>
      </div>

      <BottomNav />
    </div>
  );
}






