'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase-client';
import { useAuthStore } from '@/stores/auth-store';
import { AVATARS, FREE_DAILY_LIMIT } from '@/lib/constants';
import { motion } from 'framer-motion';
import { DurationSelector } from '@/components/home/DurationSelector';
import { HomeOverlay } from '@/components/home/HomeOverlay';
import { StreakPill } from '@/components/home/StreakPill';
import { QuestPill } from '@/components/home/QuestPill';
import { CityPill } from '@/components/home/CityPill';
import { BottomNav } from '@/components/layout/BottomNav';
import { createSoloSession } from '@/lib/session-actions';
import { getCityInfo } from '@/lib/city-detection';
import type { User, UserLimit } from '@/types/database';

interface ActiveMatchInfo {
  matchId: string;
  sessionId: string;
  state: string;
}

export default function DashboardPage() {
  const router = useRouter();
  const { user, setUser } = useAuthStore();
  const [duration, setDuration] = useState(25);
  const [dailyUsed, setDailyUsed] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [isStarting, setIsStarting] = useState(false);
  const [activeMatch, setActiveMatch] = useState<ActiveMatchInfo | null>(null);
  const [questProgress, setQuestProgress] = useState({ completed: 0, total: 0 });
  const [cityActive, setCityActive] = useState<{ emoji: string; name: string; count: number } | null>(null);

  useEffect(() => {
    const supabase = createClient();

    async function load() {
      const { data: { user: authUser } } = await supabase.auth.getUser();
      if (!authUser) {
        router.push('/auth');
        return;
      }

      // User profili
      const { data: profile, error: profileError } = await supabase
        .from('users')
        .select('*')
        .eq('id', authUser.id)
        .maybeSingle();

      if (profileError) {
        console.error('Profil yüklenemedi:', profileError.message);
        if (profileError.code === '42P01' || !profile) {
          const { data: newProfile } = await supabase
            .from('users')
            .upsert({
              id: authUser.id,
              email: authUser.email ?? '',
              name: authUser.email?.split('@')[0] ?? 'Kullanıcı',
              avatar_id: 1,
            })
            .select('*')
            .single();
          if (newProfile) {
            router.push('/onboarding');
            return;
          }
        }
      } else if (profile) {
        const emailPrefix = authUser.email?.split('@')[0] || '';
        const googleName = authUser.user_metadata?.full_name || authUser.user_metadata?.name || '';
        const isAutoGenerated =
          profile.avatar_id === 1 &&
          (profile.name === emailPrefix || profile.name === googleName || profile.name === '');

        if (isAutoGenerated) {
          router.push('/onboarding');
          return;
        }

        setUser(profile as User);
      } else {
        const { data: newProfile } = await supabase
          .from('users')
          .upsert({
            id: authUser.id,
            email: authUser.email ?? '',
            name: authUser.email?.split('@')[0] ?? 'Kullanıcı',
            avatar_id: 1,
          })
          .select('*')
          .single();
        if (newProfile) setUser(newProfile as User);
      }

      // Günlük limit
      const today = new Date().toISOString().split('T')[0];
      const { data: limit } = await supabase
        .from('user_limits')
        .select('sessions_used')
        .eq('user_id', authUser.id)
        .eq('date', today)
        .maybeSingle();

      setDailyUsed((limit as UserLimit | null)?.sessions_used ?? 0);

      // Active match check
      const { data: activeMatchResult } = await supabase.rpc('get_active_match');
      if (activeMatchResult && activeMatchResult.has_active) {
        setActiveMatch({
          matchId: activeMatchResult.match_id,
          sessionId: activeMatchResult.session_id,
          state: activeMatchResult.can_rejoin ? 'broken' : 'active',
        });
      }

      // Quest progress (sadece sayı — detay Aynam'da)
      const userProfile = profile as User | null;
      if (userProfile?.metadata) {
        const meta = userProfile.metadata as {
          quests?: {
            daily?: { completed?: boolean };
            weekly?: { completed?: boolean };
          };
        };
        let completed = 0;
        let total = 0;
        if (meta.quests?.daily) {
          total++;
          if (meta.quests.daily.completed) completed++;
        }
        if (meta.quests?.weekly) {
          total++;
          if (meta.quests.weekly.completed) completed++;
        }
        setQuestProgress({ completed, total });
      }

      // Cross-page bağlantı: Home'da "Şehrin aktif" göstergesi
      if (userProfile?.metadata) {
        const cityId = (userProfile.metadata as Record<string, unknown>)?.city as string | undefined;
        if (cityId) {
          const info = getCityInfo(cityId);
          if (info) {
            const { data: atmosData } = await supabase.rpc('get_city_atmosphere', {
              p_city_id: cityId,
            });
            const cityData = atmosData as { active_now?: number } | null;
            if (cityData && (cityData.active_now ?? 0) > 0) {
              setCityActive({
                emoji: info.emoji,
                name: info.name,
                count: cityData.active_now ?? 0,
              });
            }
          }
        }
      }

      setIsLoading(false);
    }

    load();
  }, [router, setUser]);

  const canStartSession = user?.is_premium || dailyUsed < FREE_DAILY_LIMIT;
  const isRestricted = user && user.trust_score < 50;
  const avatar = AVATARS.find(a => a.id === user?.avatar_id) ?? AVATARS[0];

  const handleSoloStart = async () => {
    if (!user || !canStartSession || isRestricted || isStarting) return;
    setIsStarting(true);
    const sessionId = await createSoloSession(user.id, duration);
    if (sessionId) {
      router.push(`/session/prepare?id=${sessionId}&solo=true&duration=${duration}`);
    }
    setIsStarting(false);
  };

  const handleMatchStart = () => {
    if (!canStartSession || isRestricted) return;
    router.push(`/session/quick-match?duration=${duration}`);
  };

  const handleRejoin = async () => {
    if (!activeMatch) return;
    if (activeMatch.state === 'active') {
      router.push(`/session/active?id=${activeMatch.sessionId}`);
    } else if (activeMatch.state === 'preparing') {
      router.push(`/session/prepare?id=${activeMatch.sessionId}`);
    } else if (activeMatch.state === 'broken') {
      const supabase = createClient();
      const { data, error } = await supabase.rpc('rejoin_match', {
        p_match_id: activeMatch.matchId,
      });
      if (error || !(data as { success: boolean })?.success) {
        setActiveMatch(null);
        return;
      }
      router.push(`/session/active?id=${activeMatch.sessionId}`);
    }
  };

  const handleDismissMatch = async () => {
    if (!activeMatch) return;
    const supabase = createClient();
    await supabase.rpc('complete_match', { p_match_id: activeMatch.matchId });
    await supabase
      .from('sessions')
      .update({ status: 'abandoned', ended_at: new Date().toISOString() })
      .eq('id', activeMatch.sessionId)
      .in('status', ['waiting', 'preparing', 'active']);
    setActiveMatch(null);
  };

  if (isLoading || !user) {
    return (
      <div className="min-h-screen bg-[#1a1a2e] flex items-center justify-center">
        <div className="text-white/50 text-lg">Yükleniyor...</div>
      </div>
    );
  }

  return (
    <div className="relative min-h-screen overflow-hidden">
      {/* Background Image */}
      <div
        className="absolute inset-0 bg-cover bg-center bg-no-repeat"
        style={{ backgroundImage: "url('/images/backgrounds/sunset-office.jpg')" }}
      />
      <div className="absolute inset-0 bg-gradient-to-b from-black/40 via-black/20 to-black/60" />

      {/* Content */}
      <div className="relative z-10 min-h-screen flex flex-col px-4 pb-24">
        <div className="max-w-sm mx-auto w-full flex-1 flex flex-col">
          {/* Top Overlay */}
          <HomeOverlay avatarEmoji={avatar.emoji} userName={user.name} />

          {/* Active match rejoin banner */}
          {activeMatch && (
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-orange-500/15 border border-orange-500/30 rounded-xl p-3 mb-4 backdrop-blur-sm"
            >
              <div className="flex items-center gap-3">
                <span className="text-xl">{activeMatch.state === 'active' ? '⏱️' : '🔄'}</span>
                <div className="flex-1">
                  <p className="text-white text-sm font-medium">
                    {activeMatch.state === 'active'
                      ? 'Devam eden seansın var!'
                      : 'Eşleşmeye geri dönebilirsin!'}
                  </p>
                </div>
                <div className="flex flex-col gap-1">
                  <button
                    onClick={handleRejoin}
                    className="bg-[#ffcb77] text-[#1a1a2e] px-3 py-1.5 rounded-lg text-xs font-semibold"
                  >
                    Geri Dön
                  </button>
                  <button
                    onClick={handleDismissMatch}
                    className="text-gray-400 text-[10px] hover:text-gray-200 transition-colors"
                  >
                    Kapat
                  </button>
                </div>
              </div>
            </motion.div>
          )}

          {/* Spacer */}
          <div className="flex-1" />

          {/* Pills row */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3 }}
            className="flex flex-wrap items-center justify-center gap-2 mb-8"
          >
            <StreakPill streak={user.current_streak} />
            <QuestPill completed={questProgress.completed} total={questProgress.total} />
            {cityActive && (
              <CityPill
                cityEmoji={cityActive.emoji}
                cityName={cityActive.name}
                activeCount={cityActive.count}
              />
            )}
          </motion.div>

          {/* Duration Selector */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mb-6"
          >
            <p className="text-white/40 text-xs text-center mb-3">dakika</p>
            <DurationSelector selected={duration} onChange={setDuration} />
          </motion.div>

          {/* CTAs */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.35 }}
            className="space-y-3 mb-6"
          >
            <motion.button
              whileHover={{ scale: canStartSession && !isRestricted ? 1.02 : 1 }}
              whileTap={{ scale: canStartSession && !isRestricted ? 0.98 : 1 }}
              onClick={handleSoloStart}
              disabled={!canStartSession || !!isRestricted || isStarting}
              className={`w-full py-4 rounded-2xl font-semibold text-lg transition-all ${
                canStartSession && !isRestricted
                  ? 'bg-[#ffcb77] text-[#1a1a2e] shadow-lg shadow-[#ffcb77]/25'
                  : 'bg-white/10 text-gray-500 cursor-not-allowed'
              }`}
            >
              {isStarting ? 'Başlatılıyor...' : 'Solo Başla'}
            </motion.button>

            {!isRestricted && (
              <motion.button
                whileHover={{ scale: canStartSession ? 1.02 : 1 }}
                whileTap={{ scale: canStartSession ? 0.98 : 1 }}
                onClick={handleMatchStart}
                disabled={!canStartSession}
                className={`w-full py-3.5 rounded-2xl font-medium text-base transition-all border ${
                  canStartSession
                    ? 'border-white/20 text-white/80 hover:bg-white/5 backdrop-blur-sm'
                    : 'border-white/5 text-gray-600 cursor-not-allowed'
                }`}
              >
                Eşleşme Bul
              </motion.button>
            )}
          </motion.div>

          {/* Daily limit info */}
          {!user.is_premium && (
            <p className="text-white/30 text-xs text-center mb-2">
              Bugün: {dailyUsed}/{FREE_DAILY_LIMIT} seans
            </p>
          )}

          {!canStartSession && (
            <p className="text-white/20 text-xs text-center">
              Yarın tekrar gel veya premium&apos;a geç.
            </p>
          )}

          {/* Bottom spacer */}
          <div className="flex-1" />
        </div>
      </div>

      <BottomNav />
    </div>
  );
}
